//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Obligation collateral state
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ObligationCollateral {
/// Reserve collateral is deposited to
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub deposit_reserve: Pubkey,
/// Amount of collateral deposited
pub deposited_amount: u64,
/// Collateral market value in quote currency (scaled fraction)
pub market_value_sf: u128,
/// Debt amount (lamport) taken against this collateral.
/// (only meaningful if this obligation is part of an elevation group, otherwise 0)
/// This is only indicative of the debt computed on the last refresh obligation.
/// If the obligation have multiple collateral this value is the same for all of them.
pub borrowed_amount_against_this_collateral_in_elevation_group: u64,
pub padding: [u64; 9],
}


