//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::InitObligationArgs;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const INIT_OBLIGATION_DISCRIMINATOR: [u8; 8] = [251, 10, 231, 76, 27, 11, 159, 96];

/// Accounts.
#[derive(Debug)]
pub struct InitObligation {
      
              
          pub obligation_owner: solana_pubkey::Pubkey,
          
              
          pub fee_payer: solana_pubkey::Pubkey,
          
              
          pub obligation: solana_pubkey::Pubkey,
          
              
          pub lending_market: solana_pubkey::Pubkey,
          
              
          pub seed1_account: solana_pubkey::Pubkey,
          
              
          pub seed2_account: solana_pubkey::Pubkey,
          
              
          pub owner_user_metadata: solana_pubkey::Pubkey,
          
              
          pub rent: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl InitObligation {
  pub fn instruction(&self, args: InitObligationInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: InitObligationInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(9+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.obligation_owner,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.obligation,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.lending_market,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.seed1_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.seed2_account,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.owner_user_metadata,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.rent,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&InitObligationInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::KAMINO_LENDING_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct InitObligationInstructionData {
            discriminator: [u8; 8],
            }

impl InitObligationInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [251, 10, 231, 76, 27, 11, 159, 96],
                                }
  }
}

impl Default for InitObligationInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct InitObligationInstructionArgs {
                  pub args: InitObligationArgs,
      }


/// Instruction builder for `InitObligation`.
///
/// ### Accounts:
///
                ///   0. `[signer]` obligation_owner
                      ///   1. `[writable, signer]` fee_payer
                ///   2. `[writable]` obligation
          ///   3. `[]` lending_market
          ///   4. `[]` seed1_account
          ///   5. `[]` seed2_account
          ///   6. `[]` owner_user_metadata
          ///   7. `[]` rent
          ///   8. `[]` system_program
#[derive(Clone, Debug, Default)]
pub struct InitObligationBuilder {
            obligation_owner: Option<solana_pubkey::Pubkey>,
                fee_payer: Option<solana_pubkey::Pubkey>,
                obligation: Option<solana_pubkey::Pubkey>,
                lending_market: Option<solana_pubkey::Pubkey>,
                seed1_account: Option<solana_pubkey::Pubkey>,
                seed2_account: Option<solana_pubkey::Pubkey>,
                owner_user_metadata: Option<solana_pubkey::Pubkey>,
                rent: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                        args: Option<InitObligationArgs>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitObligationBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn obligation_owner(&mut self, obligation_owner: solana_pubkey::Pubkey) -> &mut Self {
                        self.obligation_owner = Some(obligation_owner);
                    self
    }
            #[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_payer = Some(fee_payer);
                    self
    }
            #[inline(always)]
    pub fn obligation(&mut self, obligation: solana_pubkey::Pubkey) -> &mut Self {
                        self.obligation = Some(obligation);
                    self
    }
            #[inline(always)]
    pub fn lending_market(&mut self, lending_market: solana_pubkey::Pubkey) -> &mut Self {
                        self.lending_market = Some(lending_market);
                    self
    }
            #[inline(always)]
    pub fn seed1_account(&mut self, seed1_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.seed1_account = Some(seed1_account);
                    self
    }
            #[inline(always)]
    pub fn seed2_account(&mut self, seed2_account: solana_pubkey::Pubkey) -> &mut Self {
                        self.seed2_account = Some(seed2_account);
                    self
    }
            #[inline(always)]
    pub fn owner_user_metadata(&mut self, owner_user_metadata: solana_pubkey::Pubkey) -> &mut Self {
                        self.owner_user_metadata = Some(owner_user_metadata);
                    self
    }
            #[inline(always)]
    pub fn rent(&mut self, rent: solana_pubkey::Pubkey) -> &mut Self {
                        self.rent = Some(rent);
                    self
    }
            #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn args(&mut self, args: InitObligationArgs) -> &mut Self {
        self.args = Some(args);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = InitObligation {
                              obligation_owner: self.obligation_owner.expect("obligation_owner is not set"),
                                        fee_payer: self.fee_payer.expect("fee_payer is not set"),
                                        obligation: self.obligation.expect("obligation is not set"),
                                        lending_market: self.lending_market.expect("lending_market is not set"),
                                        seed1_account: self.seed1_account.expect("seed1_account is not set"),
                                        seed2_account: self.seed2_account.expect("seed2_account is not set"),
                                        owner_user_metadata: self.owner_user_metadata.expect("owner_user_metadata is not set"),
                                        rent: self.rent.expect("rent is not set"),
                                        system_program: self.system_program.expect("system_program is not set"),
                      };
          let args = InitObligationInstructionArgs {
                                                              args: self.args.clone().expect("args is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `init_obligation` CPI accounts.
  pub struct InitObligationCpiAccounts<'a, 'b> {
          
                    
              pub obligation_owner: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub obligation: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub lending_market: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub seed1_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub seed2_account: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub owner_user_metadata: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub rent: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `init_obligation` CPI instruction.
pub struct InitObligationCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub obligation_owner: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub fee_payer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub obligation: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub lending_market: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub seed1_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub seed2_account: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub owner_user_metadata: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub rent: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: InitObligationInstructionArgs,
  }

impl<'a, 'b> InitObligationCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: InitObligationCpiAccounts<'a, 'b>,
              args: InitObligationInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              obligation_owner: accounts.obligation_owner,
              fee_payer: accounts.fee_payer,
              obligation: accounts.obligation,
              lending_market: accounts.lending_market,
              seed1_account: accounts.seed1_account,
              seed2_account: accounts.seed2_account,
              owner_user_metadata: accounts.owner_user_metadata,
              rent: accounts.rent,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(9+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.obligation_owner.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.obligation.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.lending_market.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.seed1_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.seed2_account.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.owner_user_metadata.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.rent.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&InitObligationInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::KAMINO_LENDING_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(10 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.obligation_owner.clone());
                        account_infos.push(self.fee_payer.clone());
                        account_infos.push(self.obligation.clone());
                        account_infos.push(self.lending_market.clone());
                        account_infos.push(self.seed1_account.clone());
                        account_infos.push(self.seed2_account.clone());
                        account_infos.push(self.owner_user_metadata.clone());
                        account_infos.push(self.rent.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `InitObligation` via CPI.
///
/// ### Accounts:
///
                ///   0. `[signer]` obligation_owner
                      ///   1. `[writable, signer]` fee_payer
                ///   2. `[writable]` obligation
          ///   3. `[]` lending_market
          ///   4. `[]` seed1_account
          ///   5. `[]` seed2_account
          ///   6. `[]` owner_user_metadata
          ///   7. `[]` rent
          ///   8. `[]` system_program
#[derive(Clone, Debug)]
pub struct InitObligationCpiBuilder<'a, 'b> {
  instruction: Box<InitObligationCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitObligationCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(InitObligationCpiBuilderInstruction {
      __program: program,
              obligation_owner: None,
              fee_payer: None,
              obligation: None,
              lending_market: None,
              seed1_account: None,
              seed2_account: None,
              owner_user_metadata: None,
              rent: None,
              system_program: None,
                                            args: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn obligation_owner(&mut self, obligation_owner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.obligation_owner = Some(obligation_owner);
                    self
    }
      #[inline(always)]
    pub fn fee_payer(&mut self, fee_payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_payer = Some(fee_payer);
                    self
    }
      #[inline(always)]
    pub fn obligation(&mut self, obligation: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.obligation = Some(obligation);
                    self
    }
      #[inline(always)]
    pub fn lending_market(&mut self, lending_market: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lending_market = Some(lending_market);
                    self
    }
      #[inline(always)]
    pub fn seed1_account(&mut self, seed1_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.seed1_account = Some(seed1_account);
                    self
    }
      #[inline(always)]
    pub fn seed2_account(&mut self, seed2_account: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.seed2_account = Some(seed2_account);
                    self
    }
      #[inline(always)]
    pub fn owner_user_metadata(&mut self, owner_user_metadata: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.owner_user_metadata = Some(owner_user_metadata);
                    self
    }
      #[inline(always)]
    pub fn rent(&mut self, rent: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent = Some(rent);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn args(&mut self, args: InitObligationArgs) -> &mut Self {
        self.instruction.args = Some(args);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = InitObligationInstructionArgs {
                                                              args: self.instruction.args.clone().expect("args is not set"),
                                    };
        let instruction = InitObligationCpi {
        __program: self.instruction.__program,
                  
          obligation_owner: self.instruction.obligation_owner.expect("obligation_owner is not set"),
                  
          fee_payer: self.instruction.fee_payer.expect("fee_payer is not set"),
                  
          obligation: self.instruction.obligation.expect("obligation is not set"),
                  
          lending_market: self.instruction.lending_market.expect("lending_market is not set"),
                  
          seed1_account: self.instruction.seed1_account.expect("seed1_account is not set"),
                  
          seed2_account: self.instruction.seed2_account.expect("seed2_account is not set"),
                  
          owner_user_metadata: self.instruction.owner_user_metadata.expect("owner_user_metadata is not set"),
                  
          rent: self.instruction.rent.expect("rent is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct InitObligationCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            obligation_owner: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                obligation: Option<&'b solana_account_info::AccountInfo<'a>>,
                lending_market: Option<&'b solana_account_info::AccountInfo<'a>>,
                seed1_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                seed2_account: Option<&'b solana_account_info::AccountInfo<'a>>,
                owner_user_metadata: Option<&'b solana_account_info::AccountInfo<'a>>,
                rent: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        args: Option<InitObligationArgs>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

