//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const WITHDRAW_PROTOCOL_FEE_DISCRIMINATOR: [u8; 8] = [158, 201, 158, 189, 33, 93, 162, 103];

/// Accounts.
#[derive(Debug)]
pub struct WithdrawProtocolFee {
      
              
          pub global_config: solana_pubkey::Pubkey,
          
              
          pub lending_market: solana_pubkey::Pubkey,
          
              
          pub reserve: solana_pubkey::Pubkey,
          
              
          pub reserve_liquidity_mint: solana_pubkey::Pubkey,
          
              
          pub lending_market_authority: solana_pubkey::Pubkey,
          
              
          pub fee_vault: solana_pubkey::Pubkey,
          
              
          pub fee_collector_ata: solana_pubkey::Pubkey,
          
              
          pub token_program: solana_pubkey::Pubkey,
      }

impl WithdrawProtocolFee {
  pub fn instruction(&self, args: WithdrawProtocolFeeInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: WithdrawProtocolFeeInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(8+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.global_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.lending_market,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.reserve,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.reserve_liquidity_mint,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.lending_market_authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_vault,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.fee_collector_ata,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&WithdrawProtocolFeeInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::KAMINO_LENDING_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct WithdrawProtocolFeeInstructionData {
            discriminator: [u8; 8],
            }

impl WithdrawProtocolFeeInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [158, 201, 158, 189, 33, 93, 162, 103],
                                }
  }
}

impl Default for WithdrawProtocolFeeInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct WithdrawProtocolFeeInstructionArgs {
                  pub amount: u64,
      }


/// Instruction builder for `WithdrawProtocolFee`.
///
/// ### Accounts:
///
          ///   0. `[]` global_config
          ///   1. `[]` lending_market
          ///   2. `[]` reserve
          ///   3. `[]` reserve_liquidity_mint
          ///   4. `[]` lending_market_authority
                ///   5. `[writable]` fee_vault
                ///   6. `[writable]` fee_collector_ata
          ///   7. `[]` token_program
#[derive(Clone, Debug, Default)]
pub struct WithdrawProtocolFeeBuilder {
            global_config: Option<solana_pubkey::Pubkey>,
                lending_market: Option<solana_pubkey::Pubkey>,
                reserve: Option<solana_pubkey::Pubkey>,
                reserve_liquidity_mint: Option<solana_pubkey::Pubkey>,
                lending_market_authority: Option<solana_pubkey::Pubkey>,
                fee_vault: Option<solana_pubkey::Pubkey>,
                fee_collector_ata: Option<solana_pubkey::Pubkey>,
                token_program: Option<solana_pubkey::Pubkey>,
                        amount: Option<u64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl WithdrawProtocolFeeBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn global_config(&mut self, global_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.global_config = Some(global_config);
                    self
    }
            #[inline(always)]
    pub fn lending_market(&mut self, lending_market: solana_pubkey::Pubkey) -> &mut Self {
                        self.lending_market = Some(lending_market);
                    self
    }
            #[inline(always)]
    pub fn reserve(&mut self, reserve: solana_pubkey::Pubkey) -> &mut Self {
                        self.reserve = Some(reserve);
                    self
    }
            #[inline(always)]
    pub fn reserve_liquidity_mint(&mut self, reserve_liquidity_mint: solana_pubkey::Pubkey) -> &mut Self {
                        self.reserve_liquidity_mint = Some(reserve_liquidity_mint);
                    self
    }
            #[inline(always)]
    pub fn lending_market_authority(&mut self, lending_market_authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.lending_market_authority = Some(lending_market_authority);
                    self
    }
            #[inline(always)]
    pub fn fee_vault(&mut self, fee_vault: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_vault = Some(fee_vault);
                    self
    }
            #[inline(always)]
    pub fn fee_collector_ata(&mut self, fee_collector_ata: solana_pubkey::Pubkey) -> &mut Self {
                        self.fee_collector_ata = Some(fee_collector_ata);
                    self
    }
            #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
                    #[inline(always)]
      pub fn amount(&mut self, amount: u64) -> &mut Self {
        self.amount = Some(amount);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = WithdrawProtocolFee {
                              global_config: self.global_config.expect("global_config is not set"),
                                        lending_market: self.lending_market.expect("lending_market is not set"),
                                        reserve: self.reserve.expect("reserve is not set"),
                                        reserve_liquidity_mint: self.reserve_liquidity_mint.expect("reserve_liquidity_mint is not set"),
                                        lending_market_authority: self.lending_market_authority.expect("lending_market_authority is not set"),
                                        fee_vault: self.fee_vault.expect("fee_vault is not set"),
                                        fee_collector_ata: self.fee_collector_ata.expect("fee_collector_ata is not set"),
                                        token_program: self.token_program.expect("token_program is not set"),
                      };
          let args = WithdrawProtocolFeeInstructionArgs {
                                                              amount: self.amount.clone().expect("amount is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `withdraw_protocol_fee` CPI accounts.
  pub struct WithdrawProtocolFeeCpiAccounts<'a, 'b> {
          
                    
              pub global_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub lending_market: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub reserve: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub reserve_liquidity_mint: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub lending_market_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub fee_vault: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub fee_collector_ata: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `withdraw_protocol_fee` CPI instruction.
pub struct WithdrawProtocolFeeCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub global_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub lending_market: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub reserve: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub reserve_liquidity_mint: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub lending_market_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub fee_vault: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub fee_collector_ata: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: WithdrawProtocolFeeInstructionArgs,
  }

impl<'a, 'b> WithdrawProtocolFeeCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: WithdrawProtocolFeeCpiAccounts<'a, 'b>,
              args: WithdrawProtocolFeeInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              global_config: accounts.global_config,
              lending_market: accounts.lending_market,
              reserve: accounts.reserve,
              reserve_liquidity_mint: accounts.reserve_liquidity_mint,
              lending_market_authority: accounts.lending_market_authority,
              fee_vault: accounts.fee_vault,
              fee_collector_ata: accounts.fee_collector_ata,
              token_program: accounts.token_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(8+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.global_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.lending_market.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.reserve.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.reserve_liquidity_mint.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.lending_market_authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_vault.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.fee_collector_ata.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&WithdrawProtocolFeeInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::KAMINO_LENDING_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(9 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.global_config.clone());
                        account_infos.push(self.lending_market.clone());
                        account_infos.push(self.reserve.clone());
                        account_infos.push(self.reserve_liquidity_mint.clone());
                        account_infos.push(self.lending_market_authority.clone());
                        account_infos.push(self.fee_vault.clone());
                        account_infos.push(self.fee_collector_ata.clone());
                        account_infos.push(self.token_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `WithdrawProtocolFee` via CPI.
///
/// ### Accounts:
///
          ///   0. `[]` global_config
          ///   1. `[]` lending_market
          ///   2. `[]` reserve
          ///   3. `[]` reserve_liquidity_mint
          ///   4. `[]` lending_market_authority
                ///   5. `[writable]` fee_vault
                ///   6. `[writable]` fee_collector_ata
          ///   7. `[]` token_program
#[derive(Clone, Debug)]
pub struct WithdrawProtocolFeeCpiBuilder<'a, 'b> {
  instruction: Box<WithdrawProtocolFeeCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> WithdrawProtocolFeeCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(WithdrawProtocolFeeCpiBuilderInstruction {
      __program: program,
              global_config: None,
              lending_market: None,
              reserve: None,
              reserve_liquidity_mint: None,
              lending_market_authority: None,
              fee_vault: None,
              fee_collector_ata: None,
              token_program: None,
                                            amount: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn global_config(&mut self, global_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.global_config = Some(global_config);
                    self
    }
      #[inline(always)]
    pub fn lending_market(&mut self, lending_market: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lending_market = Some(lending_market);
                    self
    }
      #[inline(always)]
    pub fn reserve(&mut self, reserve: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.reserve = Some(reserve);
                    self
    }
      #[inline(always)]
    pub fn reserve_liquidity_mint(&mut self, reserve_liquidity_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.reserve_liquidity_mint = Some(reserve_liquidity_mint);
                    self
    }
      #[inline(always)]
    pub fn lending_market_authority(&mut self, lending_market_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lending_market_authority = Some(lending_market_authority);
                    self
    }
      #[inline(always)]
    pub fn fee_vault(&mut self, fee_vault: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_vault = Some(fee_vault);
                    self
    }
      #[inline(always)]
    pub fn fee_collector_ata(&mut self, fee_collector_ata: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.fee_collector_ata = Some(fee_collector_ata);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
                    #[inline(always)]
      pub fn amount(&mut self, amount: u64) -> &mut Self {
        self.instruction.amount = Some(amount);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = WithdrawProtocolFeeInstructionArgs {
                                                              amount: self.instruction.amount.clone().expect("amount is not set"),
                                    };
        let instruction = WithdrawProtocolFeeCpi {
        __program: self.instruction.__program,
                  
          global_config: self.instruction.global_config.expect("global_config is not set"),
                  
          lending_market: self.instruction.lending_market.expect("lending_market is not set"),
                  
          reserve: self.instruction.reserve.expect("reserve is not set"),
                  
          reserve_liquidity_mint: self.instruction.reserve_liquidity_mint.expect("reserve_liquidity_mint is not set"),
                  
          lending_market_authority: self.instruction.lending_market_authority.expect("lending_market_authority is not set"),
                  
          fee_vault: self.instruction.fee_vault.expect("fee_vault is not set"),
                  
          fee_collector_ata: self.instruction.fee_collector_ata.expect("fee_collector_ata is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct WithdrawProtocolFeeCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            global_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                lending_market: Option<&'b solana_account_info::AccountInfo<'a>>,
                reserve: Option<&'b solana_account_info::AccountInfo<'a>>,
                reserve_liquidity_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
                lending_market_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
                fee_collector_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        amount: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

