//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub mod accounts;
pub mod errors;
pub mod instructions;
pub mod programs;
pub mod shared;
pub mod types;

// Re-export under "generated" for compatibility
pub mod generated {
    pub use crate::accounts;
    pub use crate::errors;
    pub use crate::instructions;
    pub use crate::programs;
    pub use crate::shared;
    pub use crate::types;
}

pub(crate) use programs::*;
